Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам: оценка 2 и ниже — низкий рейтинг; оценка 4 и ниже — средний рейтинг; оценка 4.5 и 5 — высокий рейтинг.

In [1]:
import pandas as pd
ratings = pd.read_csv('ratings.csv') 
movies = pd.read_csv('movies.csv') 

def class_film(rating):
    if rating <=2: 
        result='низкий рейтинг'
    elif rating <=4: 
        result='средний рейтинг'
    else:
        result='высокий рейтинг'
    return result
ratings['class'] = ratings['rating'].apply(class_film)
ratings = ratings.merge(movies, on='movieId', how='left')
ratings[['userId', 'title', 'rating', 'class']]

,userId,title,rating,class
0,1,Dangerous Minds (1995),2.5,средний рейтинг
1,1,Dumbo (1941),3.0,средний рейтинг
2,1,Sleepers (1996),3.0,средний рейтинг
3,1,Escape from New York (1981),2.0,низкий рейтинг
4,1,Cinema Paradiso (Nuovo cinema Paradiso) (1989),4.0,средний рейтинг
...,...,...,...,...
99999,671,Raising Victor Vargas (2002),2.5,средний рейтинг
100000,671,Stevie (2002),4.0,средний рейтинг
100001,671,"Matrix Reloaded, The (2003)",4.0,средний рейтинг
100002,671,Whale Rider (2002),2.5,средний рейтинг
100003,671,Seabiscuit (2003),3.5,средний рейтинг

Нужно написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определённому региону. 
Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.
Результат классификации запишите в отдельный столбец region.

In [2]:
import pandas as pd
keyw = pd.read_csv('keywords.csv', sep=',') 
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}
def geo(keyword):
    keyword_lower = str(keyword).lower() # перевожу значение столбца в строчку и маленькими буквами
    words = keyword_lower.split() # Список слов для поиска
    for region, cities in geo_data.items():
        for city in cities:  # Проверяем каждый город в текущем регионе
            if city in words:
                return region 
    return 'undefined'
keyw['region'] = keyw['keyword'].apply(geo)
keyw

                       keyword     shows     region
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
...                        ...       ...        ...
99995   эльдорадо старый оскол      3705  undefined
99996      frigate для firefox      3630  undefined
99997                   укрсиб      3630  undefined
99998  погода в ялте на неделю      3688  undefined
99999                     ггму      3630  undefined

[100000 rows x 3 columns]